name: Deploy Java backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64, prod, server-55]
    if: contains(github.event.head_commit.message, '#deploy')
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'


      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: |
          docker build  --no-cache -t ghcr.io/bayrtsogt/landing-service:latest .

      - name: Push Docker image
        run: docker push --disable-content-trust=true ghcr.io/bayrtsogt/landing-service:latest

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/bayrtsogt/landing-service:latest

      - name: Stop and remove existing container
        run: |
          docker ps --quiet --filter "name=landing-backend" | ForEach-Object { docker rm -f $_ }

      - name: Run Docker container
        run: |
          docker run -d -p 8088:8088  --restart always --name landing-backend ghcr.io/bayrtsogt/landing-service:latest

      - name: Cleanup old Docker images
        run: |
          docker image prune -f